export const BROAD_ANCESTRY_MAPPING: Record<string, string> = {
"European":"European",
"South Asian":"South Asian",
"European, South Asian":"Multi-Ancestry (including European)",
"East Asian":"East Asian",
"Hispanic or Latin American":"Hispanic or Latin American",
"African American or Afro-Caribbean":"African",
"Greater Middle Eastern (Middle Eastern, North African or Persian)":"Greater Middle Eastern (Middle Eastern, North African or Persian)",
"European, NR":"Multi-Ancestry (including European)",
"African unspecified":"African",
"European, African American or Afro-Caribbean, East Asian, Hispanic or Latin American, South Asian":"Multi-Ancestry (including European)",
"European, Other":"Multi-Ancestry (including European)",
"Asian unspecified":"Additional Asian Ancestries (including Central, and South East Asian)",
"Sub-Saharan African, African American or Afro-Caribbean":"African",
"NR":"Ancestry Not Reported",
"European, South Asian, East Asian, African American or Afro-Caribbean":"Multi-Ancestry (including European)",
"Other":"Additional Diverse Ancestries",
"African American or Afro-Caribbean, Asian unspecified":"Multi-Ancestry (excluding European)",
"NR, Hispanic or Latin American, African unspecified, Asian unspecified":"Multi-Ancestry (excluding European)",
"European, East Asian, South Asian, Asian unspecified, NR":"Multi-Ancestry (including European)",
"European, South Asian, NR":"Multi-Ancestry (including European)",
"South Asian, South East Asian, East Asian":"Additional Asian Ancestries (including Central, and South East Asian)",
"African American or Afro-Caribbean, African unspecified":"African",
"Hispanic or Latin American, African unspecified, Asian unspecified, NR":"Multi-Ancestry (excluding European)",
"European, African American or Afro-Caribbean, Hispanic or Latin American, South Asian":"Multi-Ancestry (including European)",
"European, African American or Afro-Caribbean, Hispanic or Latin American":"Multi-Ancestry (including European)",
"European, African unspecified, Asian unspecified, NR":"Multi-Ancestry (including European)",
"Other admixed ancestry":"Additional Asian Ancestries (including Central, and South East Asian)",
"Not reported":"Ancestry Not Reported",
"European, South Asian, African unspecified, East Asian, Other admixed ancestry, NR":"Multi-Ancestry (including European)",
"African unspecified, African American or Afro-Caribbean":"African",
"Sub-Saharan African":"African",
"African American or Afro-Caribbean, African unspecified, European":"Multi-Ancestry (including European)",
"South East Asian":"Additional Asian Ancestries (including Central, and South East Asian)",
"Hispanic or Latin American, Native American":"Multi-Ancestry (excluding European)",
"East Asian, NR":"Multi-Ancestry (excluding European)",
"East Asian, South Asian":"Multi-Ancestry (excluding European)",
"European, Hispanic or Latin American":"Multi-Ancestry (including European)",
"Native American":"Additional Diverse Ancestries",
"African American or Afro-Caribbean, East Asian, European, Hispanic or Latin American, South Asian, NR":"Multi-Ancestry (including European)",
"African unspecified, East Asian, European, Hispanic or Latin American, South Asian":"Multi-Ancestry (including European)",
"European, South East Asian, East Asian, South Asian, African American or Afro-Caribbean, Native American, Greater Middle Eastern (Middle Eastern, North African or Persian), Hispanic or Latin American, Not reported":"Multi-Ancestry (including European)",
"African American or Afro-Caribbean, Hispanic or Latin American":"Multi-Ancestry (excluding European)",
"European, Asian unspecified":"Multi-Ancestry (including European)",
"Hispanic or Latin American, African unspecified":"Multi-Ancestry (excluding European)",
"European, African unspecified, Asian unspecified, Other admixed ancestry, Not reported":"Multi-Ancestry (including European)",
"South Asian, East Asian, African American or Afro-Caribbean, Hispanic or Latin American":"Multi-Ancestry (excluding European)",
"African unspecified, Hispanic or Latin American, European, Asian unspecified, NR":"Multi-Ancestry (including European)",
"African American or Afro-Caribbean, European, Hispanic or Latin American":"Multi-Ancestry (including European)",
"European, East Asian, African unspecified, Hispanic or Latin American, South Asian":"Multi-Ancestry (including European)",
"European, African unspecified, Hispanic or Latin American, East Asian, South Asian":"Multi-Ancestry (including European)",
"European, East Asian, African unspecified, South Asian, Greater Middle Eastern (Middle Eastern, North African or Persian)":"Multi-Ancestry (including European)",
"African American or Afro-Caribbean,African unspecified":"African",
"European, Hispanic or Latin American, African unspecified, East Asian, Oceanian, Not reported":"Multi-Ancestry (including European)",
"European, East Asian, Hispanic or Latin American, African unspecified, South Asian":"Multi-Ancestry (including European)",
"East Asian, European":"",
"European, African unspecified, East Asian, South Asian, Not reported":"Multi-Ancestry (including European)",
"South Asian,East Asian":"Multi-Ancestry (excluding European)",
"South Asian, East Asian, African unspecified":"Multi-Ancestry (excluding European)",
"Asian unspecified, Oceanian":"Additional Diverse Ancestries",
"African American or Afro-Caribbean, African unspecified, European, East Asian, Hispanic or Latin American, South Asian":"Multi-Ancestry (including European)",
"African American or Afro-Caribbean, East Asian, European, Hispanic or Latin American, South Asian":"Multi-Ancestry (including European)",
"African American or Afro-Caribbean, East Asian, European, Hispanic or Latin American, South Asian, Sub-Saharan African":"Multi-Ancestry (including European)",
"Central Asian, South Asian":"Additional Asian Ancestries (including Central, and South East Asian)",
"European, African unspecified, East Asian, Hispanic or Latin American":"Multi-Ancestry (including European)",
"European, African American or Afro-Caribbean, Hispanic or Latin American, East Asian, South Asian":"Multi-Ancestry (including European)",
"European, Hispanic or Latin American, African American or Afro-Caribbean":"Multi-Ancestry (including European)",
"East Asian, Asian unspecified":"Multi-Ancestry (excluding European)",
"Oceanian":"Additional Diverse Ancestries",
"European, South Asian, African unspecified, Other admixed ancestry":"Multi-Ancestry (including European)",
"European, African unspecified, East Asian, European, Hispanic or Latin American":"Multi-Ancestry (including European)",
"European, African unspecified, East Asian, South Asian, Greater Middle Eastern (Middle Eastern, North African or Persian), Hispanic or Latin American":"Multi-Ancestry (including European)",
"NR, European":"Multi-Ancestry (including European)",
"African unspecified,Hispanic or Latin American,European,South Asian,Central Asian,Greater Middle Eastern (Middle Eastern, North African or Persian),East Asian":"Multi-Ancestry (including European)",
"European, African unspecified, Asian unspecified, Oceanian, Hispanic or Latin American, Other, Not reported":"Multi-Ancestry (including European)",
"European, Central Asian":"Multi-Ancestry (including European)",
"European, Not reported":"Multi-Ancestry (including European)",
"African American or Afro-Caribbean, Sub-Saharan African":"African",
"European, East Asian, African American or Afro-Caribbean, Oceanian, Hispanic or Latin American, South Asian, African unspecified, NR":"Multi-Ancestry (including European)",
"European, East Asian, African unspecified":"Multi-Ancestry (including European)",
"European, African unspecified, NR":"Multi-Ancestry (including European)",
"European, South Asian, African American or Afro-Caribbean, African unspecified, East Asian, Asian unspecified":"Multi-Ancestry (including European)",
"European, African unspecified, South Asian, East Asian, NR":"Multi-Ancestry (including European)",
"European, African unspecified":"Multi-Ancestry (including European)",
"European, Hispanic or Latin American, African unspecified":"Multi-Ancestry (including European)",
"European, South Asian, African unspecified, East Asian, NR":"Multi-Ancestry (including European)",
"African unspecified, NR":"Multi-Ancestry (excluding European)",
"Asian unspecified, NR":"Multi-Ancestry (excluding European)",
"European, Hispanic or Latin American, African unspecified, Asian unspecified, NR":"Multi-Ancestry (including European)",
"European, Asian unspecified, Hispanic or Latin American, African unspecified, NR":"Multi-Ancestry (including European)",
"European, African unspecified, Asian unspecified, Hispanic or Latin American, NR":"Multi-Ancestry (including European)",
"European, African American or Afro-Caribbean, Hispanic or Latin American, Not reported":"Multi-Ancestry (including European)",
"European, African unspecifie“d, East Asian, South Asian":"Multi-Ancestry (including European)",
"European, African unspecified, Asian unspecified, Not reported":"Multi-Ancestry (including European)",
"African unspecified, South Asian, Greater Middle Eastern (Middle Eastern, North African or Persian)":"Multi-Ancestry (excluding European)",
"African unspecified, European, Hispanic or Latin American, African American or Afro-Caribbean, Asian unspecified":"Multi-Ancestry (excluding European)",
"European, African American or Afro-Caribbean":"Multi-Ancestry (including European)",
"South Asian, European, African unspecified, NR":"Multi-Ancestry (including European)",
"Other, NR":"Additional Diverse Ancestries",
"Native American, Asian unspecified, Oceanian, Other":"Multi-Ancestry (excluding European)",
"East Asian, South East Asian, Native American, South Asian, Other":"Multi-Ancestry (excluding European)",
"East Asian, Other admixed ancestry":"Multi-Ancestry (excluding European)",
"European, Asian unspecified, African unspecified, East Asian, Not reported":"Multi-Ancestry (including European)",
"European, Native American, African unspecified":"Multi-Ancestry (including European)",
"African American or Afro-Caribbean, Sub-Saharan African, European":"Multi-Ancestry (including European)",
"African unspecified, Hispanic or Latin American, East Asian, South Asian, European":"Multi-Ancestry (including European)",
"African American or Afro-Caribbean, Asian unspecified, European, Native American, Not reported":"Multi-Ancestry (including European)",
"European, East Asian, South Asian, Hispanic or Latin American, African unspecified":"Multi-Ancestry (including European)",
};
  

  export function normalizeAncestryBroad(raw: string): string {
    return raw
      .normalize('NFD') // remove accents
      .replace(/[\u0300-\u036f]/g, '') // remove combining characters
      .replace(/[.,;]/g, '') // remove punctuation
      .replace(/\s+/g, ' ') // collapse whitespasce
      .trim()
  }
  
export function getBroadAncestryLabelFromRaw(raw: any): string | null {
  const normalized = raw?.samples?.[0]?.ancestry_broad ?? null
  return BROAD_ANCESTRY_MAPPING[normalized] ?? null
}